### ISSUE TITLE
定时启动依然无法唤醒睡眠状态的电脑

### ISSUE THREAD

**Issue by Xiafeng-maples** [Kin-L/SGA-Sucrose_Game_Assistant#12]
> win11 专业  22H2 22621.22134      

> 未调整原计划；允许了使用定时唤醒器；调整为不需要密码         本机器执行s0睡眠，已开启休眠，推测与此无关

我额外加了一个定时启动mumu的任务，仅在手动唤醒后才开始执行。sga的定时唤醒任务没有加超过时间立即执行，因而开启后并没有看见开启的sga
前段时间尝试设置任务计划定时唤醒并启动mumu也失败了，不清楚是个例还是在win11下都有。up是否验证过_唤醒计算机运行此任务_，它被归于条件下作为判定，但在查找微软社区的一些帖子时又看见版主解释它是执行项
![屏幕截图(1)](https://github.com/Kin-L/SucroseGameAssistant/assets/159912709/b7b8e7f8-bfef-47c8-a898-8eb235c1030b)

**Comment by Kin-L** [comment]
我不太明白你的意思。
是说电脑不能自动唤醒？还是说唤醒了，但是因为唤醒超时了导致SGA没能一并打开？
关于第二段，是说你自行设置的其他计划任务在唤醒功能也有问题是吗？
另外“_唤醒计算机运行此任务_，它被归于条件下作为判定”。这个我不知道，没有了解过，也不太清楚这个概念。

我不常上github，回复会有时间不定的延迟。

**Comment by Xiafeng-maples** [comment]
单纯无法自动唤醒，目前只能是取消睡眠功能，用关闭屏幕来代替。可能还得再研究下win能不能在睡眠中被任务计划唤醒

**Comment by Kin-L** [comment]
您好，已收到您的消息，我会尽快查看。＾_＾

**Comment by Kin-L** [comment]
我的环境是win10，暂时没有win11的环境可以用来验证。我的电脑是可以正常从睡眠中被任务计划唤醒
SGA是用的我自己电脑预设好的计划任务导出为xml文件，置于SGA包体中的，在设定唤醒的时候再导入。不知道这点在win10和win11上有没有差别。
如果你自己设定其他的任务计划也不能正常唤醒，那我暂时也没啥头绪。
