### ISSUE TITLE
尘白禁区的功能模块：异常执行：实时计划

### ISSUE THREAD

**Issue by 17396743** [Kin-L/SGA-Sucrose_Game_Assistant#13]
运行后，只运行游戏后，报错异常执行：实时计划

14:30:10 | INFO | 下载完成,开始安装
14:30:12 | DEBUG | 开始初始化OCR...
14:30:12 | INFO | 安装成功:D:\Program Files\SGA\3rd_package\PaddleOCR-json_v.1.3.1(simplify)
14:30:13 | DEBUG | 初始化OCR完成
14:30:13 | INFO | 开始任务:尘白禁区
14:30:14 | INFO | 启动器打开成功
14:30:36 | DEBUG | mode 1: (0, 0, 1920, 1080)*1.0
14:30:36 | INFO | 游戏已启动
14:30:36 | INFO | 开始识别游戏状态
14:30:36 | ERROR | 任务执行异常：尘白禁区
Traceback (most recent call last):
  File "D:\Program Files\SGA\_internal\task\snow\main.py", line 25, in snow_start
    self.snow_log(60)
  File "D:\Program Files\SGA\_internal\task\snow\main.py", line 172, in snow_log
    if find_pic(r"assets\snow\picture\login2.png", (863, 370, 1059, 467), sc)[1] >= 0.6:
  File "D:\Program Files\SGA\_internal\tools\image.py", line 64, in find_pic
    tem_h, tem_w, num = template.shape
AttributeError: 'NoneType' object has no attribute 'shape'
14:30:36 | DEBUG | OCR关闭
14:30:36 | INFO | 完成任务:尘白禁区
14:30:36 | INFO | 异常执行:实时计划
14:30:37 | INFO | SGA等待 电脑无操作

**Comment by 17396743** [comment]
> 运行后，只运行游戏后，报错异常执行：实时计划
> 
> 14:30:10 | INFO | 下载完成,开始安装 14:30:12 | DEBUG | 开始初始化OCR... 14:30:12 | INFO | 安装成功:D:\Program Files\SGA\3rd_package\PaddleOCR-json_v.1.3.1(simplify) 14:30:13 | DEBUG | 初始化OCR完成 14:30:13 | INFO | 开始任务:尘白禁区 14:30:14 | INFO | 启动器打开成功 14:30:36 | DEBUG | mode 1: (0, 0, 1920, 1080)*1.0 14:30:36 | INFO | 游戏已启动 14:30:36 | INFO | 开始识别游戏状态 14:30:36 | ERROR | 任务执行异常：尘白禁区 Traceback (most recent call last): File "D:\Program Files\SGA_internal\task\snow\main.py", line 25, in snow_start self.snow_log(60) File "D:\Program Files\SGA_internal\task\snow\main.py", line 172, in snow_log if find_pic(r"assets\snow\picture\login2.png", (863, 370, 1059, 467), sc)[1] >= 0.6: File "D:\Program Files\SGA_internal\tools\image.py", line 64, in find_pic tem_h, tem_w, num = template.shape AttributeError: 'NoneType' object has no attribute 'shape' 14:30:36 | DEBUG | OCR关闭 14:30:36 | INFO | 完成任务:尘白禁区 14:30:36 | INFO | 异常执行:实时计划 14:30:37 | INFO | SGA等待 电脑无操作

识别用的图片只有6张图。只能做到启动器的更新和打开、关闭程序。

**Comment by Kin-L** [comment]
尘白模块的B服暂未适配，计划于下个版本适配。
尘白是新写的模块，大部分都用了ocr做识别，模板匹配用得比较少，所以识别用得图片比较少

**Comment by Kin-L** [comment]
已修，如果还有问题再戳我吧
