### ISSUE TITLE
自动秘境BGI疑似闪退

### ISSUE THREAD

**Issue by ufoccjipo7** [Kin-L/SGA-Sucrose_Game_Assistant#14]
BGI路径填写无误，执行自动秘境可以正常到达秘境门口和切换队伍，但是之后无反应，BGI也并未打开，LOG直接显示自动秘境任务完成，单独使用BGI可以正常运行。

**Comment by Kin-L** [comment]
看看你填的路径呢，这个不应该啊。如果能附带日志更好

**Comment by ufoccjipo7** [comment]
> 看看你填的路径呢，这个不应该啊。如果能附带日志更好

![1711033779374](https://github.com/Kin-L/SucroseGameAssistant/assets/53103662/3b4f6616-35c6-4741-8d07-090078150202)

**Comment by Kin-L** [comment]
路径应该没问题，我需要看看personal\logs目录下的日志文件。

**Comment by ufoccjipo7** [comment]
> 路径应该没问题，我需要看看personal\logs目录下的日志文件。

[2024-03-21.log](https://github.com/Kin-L/SucroseGameAssistant/files/14715259/2024-03-21.log)

**Comment by Kin-L** [comment]
我确认一下。脚本应该是进入了队伍界面，但是在点了出战之后卡住了，没能退出队伍界面是吗，然后任务停止、报错。如果是这样的话，我已经有头绪和修改方案了，有其他朋友遇到了一样的问题。

**Comment by ufoccjipo7** [comment]
> 我确认一下。脚本应该是进入了队伍界面，但是在点了出战之后卡住了，没能退出队伍界面是吗，然后任务停止、报错。如果是这样的话，我已经有头绪和修改方案了，有其他朋友遇到了一样的问题。

是这样的，期待后续改善
