### ISSUE TITLE
尘白禁区一直异常启动

### ISSUE THREAD

**Issue by 17396743** [Kin-L/SGA-Sucrose_Game_Assistant#15]
尘白禁区一直异常启动，不管如何运行都一样。
查看文件夹里面，发现没有相关数据文件。

**Comment by Kin-L** [comment]
您好，已收到您的消息，我会尽快查看。＾_＾

**Comment by Kin-L** [comment]
可以点击 全局设置 页面的 运行日志 查看详细日志，可能会有指示信息，可以看看使用说明能否解决问题。
如果无法解决可以发一下对应的日志信息和描述下异常情况，或者B站/邮箱联系我加Q群具体交流。
