### ISSUE TITLE
大佬能不能再加两个图标“归龙潮”和“新月同行”

### ISSUE THREAD

**Issue by qincenhua** [Kin-L/SGA-Sucrose_Game_Assistant#20]
求助的大佬能不能在加这两个游戏的图标？我是大佬的粉丝已经关注了

**Comment by Kin-L** [comment]
您好，已收到您的消息，我会尽快查看。＾_＾

**Comment by qincenhua** [comment]
原神大佬他没有派遣完毕而不是点击继续派遣希望能改进一下他直接弄了一个巴尼特就结束了实则还没有派遣完毕

**Comment by qincenhua** [comment]
能不能加一个自动去合成台在去凯瑟琳那里呢？

**Comment by qincenhua** [comment]
派遣有点小问题呀大佬帮我解决一下

**Comment by qincenhua** [comment]
还有这是切换一号位的时候需要我已经切换一号位才会运行切换后他选择出战没有立即返回而是退出了程序

**Comment by qincenhua** [comment]
可不可以加一个检测呀我这个已经派遣完毕了但是他没有检测到就退出程序了浓缩素质也是遇到同样的问题还有尘歌壶他找不到那里进行对话也加一个检测并前往那里毕竟有些人是不同的

**Comment by qincenhua** [comment]
三月七助手我桌面上已经安装好了能不能选择路径等待程序运行然后有一个完整运行直接点击就可以了

**Comment by qincenhua** [comment]
这个我也是测试了也可以引用其他的游戏辅助只要选择好路径直接点击<像这样的就完整运行了或者开始

**Comment by qincenhua** [comment]
这个我也是测试了也可以引用其他的游戏辅助只要选择好路径直接点击<像这样的就完整运行了或者开始

**Comment by Kin-L** [comment]
归龙巢和新月同行的脚本没有打算做。另外，除了尘白禁区的自动化，其他我都不再更新了。现在有其他合作者在帮忙更新原神的功能，如果有更新的功能会不定期一起更新。如果有需要，可以B站私信我要Q群号。

**Comment by Kin-L** [comment]
另外，如果github上代码已有更新，但是还没有发放release更新包，可以自行替换文件提前更新。具体方法就是下载代码，把其中的multithread,task,tools,task文件夹拖到SGA的_internal文件夹中，覆盖即可。

**Comment by qincenhua** [comment]
目前这两款游戏确实有这两个空缺开源项目如果大佬没有想做的打算这个空缺我也补不上在明日方舟那边模拟器是开发出了公共模板有机会还是想让大佬做一下的因为没得用我比较难受呀我觉得大佬的项目很好如果能加上就能完美了看一下能不能找到合作者做一下/QQ群大佬可以放自描文件里面不？

**Comment by qincenhua** [comment]
如果大佬能做出来的话我给大佬视频一键三连/如果实在没打算的话也不为难大佬
![Image_1729848166036](https://github.com/user-attachments/assets/07d3c49b-3362-47f3-8f68-bdd338105954)

**Comment by Kin-L** [comment]
我是没有打算做了，模拟器我也是没接触过，做不来。SGA已有的脚本都是我玩过/在玩的游戏，并不打算做不玩的游戏，如果有人愿意参与合作添加其他游戏的功能，我也是很乐意的

**Comment by qincenhua** [comment]
那大佬可以引用一些脚本不比如
鸣潮老王ok写了一个脚本
或者就是增加一个图标路径浏览功能去启动其他脚本给个建议优化吧
![IMG_20241030_031548](https://github.com/user-attachments/assets/e354d1e1-95af-4140-a20f-04c97427cece)
然后回到第一个图标运行这个脚本就运行下一个

**Comment by qincenhua** [comment]
我感觉大了好做的好像有点像启动器了所以提了一个建议优化
![Image_1730023482476](https://github.com/user-attachments/assets/68574602-31cb-433e-b529-2fe0e094f13b)

**Comment by Kin-L** [comment]
我明白你意思了，做个通用的启动项是吧，之后会弄一个。不过，因为技术力原因可能部分适配不会很到位，最好能和那个项目的作者沟通下。我个人很乐意的
