### ISSUE TITLE
脚本运行时会卡在开始识别游戏状态

### ISSUE THREAD

**Issue by Diana0725** [Kin-L/SGA-Sucrose_Game_Assistant#3]
我在使用SGA1.1.1025full的时候遇到了一些问题，即脚本会卡在开始识别游戏状态而无法继续运行。在之前的电脑上，我可以正常使用该脚本，但是在我换了新电脑之后，出现了此问题。

我使用的python版本为3.11.6，但我不确定是否有什么依赖项未安装。

我希望能得到您的帮助，谢谢。

![QQ截图20231114113626](https://github.com/Kin-L/SGA-Sucrose_Game_Assistant/assets/99268500/a009e7a6-1fed-464a-8d05-89c3c9471bfb)

**Comment by Kin-L** [comment]
我暂时无法确定具体遇到了什么问题，不过SGA即将更新2.0版本，可能问题能够解决。如果仍存在问题，建议联系我邮箱或者bilibili账号。我不常上github也暂时使用不太方便。

**Comment by Kin-L** [comment]
SGA2.0已经进入测试阶段，测试大体顺利后会将网盘链接推到github，如果希望提前体验，可以联系我邮箱（2805137028@qq.com）或者bilibili站账号（绘星痕）来获取测试版SGA网盘链接
