### ISSUE TITLE
超时报错

### ISSUE THREAD

**Issue by yemaxul** [Kin-L/SGA-Sucrose_Game_Assistant#4]
问题：
我把原神装在了机械硬盘上，读取速度较慢，偶有卡顿情况，脚本经常超时终止程序。
解决办法：
能否增加自定义步奏延迟和超时时间，避免程序直接终止。
其他问题：
在更换队伍时，可能由于卡顿原因造成更换队伍失败，卡在队伍更换界面不会自动退出。

**Comment by Kin-L** [comment]
您好，已收到您的消息，我会尽快查看。＾_＾

**Comment by yemaxul** [comment]
已经通过修改genshin.py文件的49行，把30改成90解决问题。队伍更换增加了wait时间解决。
新问题：
新发现如果进入尘歌壶后再砍树会报错退出，原因未知。
在尘歌壶中启动脚本，无法自动更换队伍，然后报错进程终止。
解决方法：
可以通过在进入游戏后先传送至七天神像重置人物和地图状态。
我过两天有空的话，可能会在fork中提交，修改后能够完整顺利运行的代码。
(❁´◡`❁)*✲ﾟ*
