### ISSUE TITLE
关于脚本界面配置与功能不明确的问题

### ISSUE THREAD

**Issue by yemaxul** [Kin-L/SGA-Sucrose_Game_Assistant#5]
看了一下up的演示视频，up的配置方式好像是一个配置文件对应一个游戏进行配置。
问题：
gui界没有注明一个配置文件是能够配置一个游戏还是多个游戏的设定。
如果我想要自定义启动顺序，是只能一个游戏对应一个配置文件来设置，然后再在顺序配置页面，进行配置才可以是吗？
那如果我一个配置文件配置了多个游戏，则脚本的运行顺序与逻辑我就无法理解了。

提议：
希望增加配置文件中对单个游戏脚本增加“开关”，有些游戏如果我不想玩的话我希望能够不启动。
配置文件最好是对单个游戏进行区分配置，然后再在一个顺序页面中弄个总配置，用于控制脚本的启动顺序。

“配置”逻辑如下：
总配置1：崩1-原2-粥3-舍2
总配置2：原1-粥2-舍1-崩2
等等
“定时”则选择“总配置”即可

崩坏的配置文件也可以移植至SGA中，通过替换M7A的config文件实现配置替换。开始可以先从实现config文件的保存与替换开始。

意见有点多，也有些乱，往大佬海涵。
感谢大佬的无私奉献，为我们的游戏日常减轻了许多压力和降低时间成本，能更专注于游戏的剧情、探索等其他非日常玩法中。
❛‿˂̵✧

**Comment by Kin-L** [comment]
是的，一个配置文件只能同时保存一个游戏的设置，只能保存 点保存按钮时 当前页面的设置信息，具体区分我是在配置文件中用一个字典值注明了该文件的保存类型，并在文件名用数字编号注明。其中0号的连续任务就是所说的总配置，连续任务可以编入其他的单独任务，执行连续任务时就会依次执行其中的单独任务。
这一点我确实没有写清楚，之后的更新会补上这部分的介绍。
关于三月七助手这方面，我确实想过把其设置移植到SGA，但是因为暂时有其他的功能我想做，个人开发，实在能力和时间都有限，所以优先级往后排了（暂时能跑就行/逃）。实际上SGA的少数代码有参考M7A，其也是python编写，如果那边的项目愿意，可以尝试将两者融合。我现在本地仓库里也有一份做了一半的UI界面。
目前SGA虽然能在我本地流畅运行，但可能在其他环境会遇到问题。还有一些我没注意到的bug等问题。感谢你的意见。

**Comment by yemaxul** [comment]
感谢
