### ISSUE TITLE
原神：自动秘境太行府错误

### ISSUE THREAD

**Issue by yemaxul** [Kin-L/SGA-Sucrose_Game_Assistant#7]
当传送到太行府后，人物不是正对副本，但能能直接按f进入秘境。
此时脚本直接按下w，人物反而远离了副本，自动秘境失败。

**Comment by Kin-L** [comment]
OK，自动秘境功能是最近才写出来的新功能，并没能测试所有情况。之后版本会依次修复。

**Comment by yemaxul** [comment]
进行了修复[详见issuse9](https://github.com/Kin-L/SucroseGameAssistant/issues/9)
