### ISSUE TITLE
未知错误导致SGA脚本终止后无法打开

### ISSUE THREAD

**Issue by yemaxul** [Kin-L/SGA-Sucrose_Game_Assistant#8]
[2024-01-29.log](https://github.com/Kin-L/SucroseGameAssistant/files/14079933/2024-01-29.log)
在运行完砍树功能后，进入自动秘境失败，进程闪退。再次启动SGA则无法进入。

**Comment by Kin-L** [comment]
自动秘境异常原因我正在定位解决，再次启动无法进入可暂时尝试在personal文件夹中删除main_config文件进行重置主配置。“再次启动SGA则无法进入”将在下次更新通过增加备份主配置的方法修复

**Comment by yemaxul** [comment]
感谢
