### ISSUE TITLE
修复低配机加载错误和太行府无法进入的错误

### ISSUE THREAD

**Issue by yemaxul** [Kin-L/SGA-Sucrose_Game_Assistant#9]
### 在[这个仓库分支](https://github.com/yemaxul/SucroseGameAssistant/tree/master/task/genshin)找到并下载

1. [domain.py](https://github.com/yemaxul/SucroseGameAssistant/blob/master/task/genshin/domain.py)
2. [genshin.py](https://github.com/yemaxul/SucroseGameAssistant/blob/master/task/genshin/genshin.py)
3. [main.py](https://github.com/yemaxul/SucroseGameAssistant/blob/master/task/genshin/main.py)
4. [team.py](https://github.com/yemaxul/SucroseGameAssistant/blob/master/task/genshin/team.py)

### 然后替换[SGA_v2.0.4_full\_internal\task\genshin](url)内对应文件即可
详细说明
[domain.py](https://github.com/yemaxul/SucroseGameAssistant/blob/master/task/genshin/domain.py)
修复了自动秘境时，太行府无法进入的问题和延长了切换队伍等待人物加载的时间。增改93行至110行
[genshin.py](https://github.com/yemaxul/SucroseGameAssistant/blob/master/task/genshin/genshin.py)
修复了低配机器地图加载超时的问题，将等待时间延长为一分半钟（90秒）。修改47行
[main.py](https://github.com/yemaxul/SucroseGameAssistant/blob/master/task/genshin/main.py)
增加开始复位功能，在脚本开始时将人物传送至枫丹庭，解决了在尘歌壶时人物更换失败的错误。增加32至34行
[team.py](https://github.com/yemaxul/SucroseGameAssistant/blob/master/task/genshin/team.py)
修复了低配机器更换队伍偶有加载超时的问题，延长了切换队伍等待人物加载的时间。修改29行

**Comment by Kin-L** [comment]
太行府的问题我已经改完，同时还有其他两个秘境也有类似问题也一同改完，稍后会更新。
地图加载等待时间延长的建议已采纳。
复位功能我认为并不是必要的。因为如果上次下线在尘歌壶，退出游戏一段时间后，下次登录是不会在尘歌壶的。除非是一直保持在尘歌壶在线或者在尘歌壶下线后短时间内上线。我认为这对于大多玩家这是多余的一个步骤，凭空消耗时间。我会在更换队伍中增加一个判断，识别联机模式。
更换队伍加载超时的问题，我注意到了。之前没注意到这一步也有加载模型的步骤。我会在这里加一个判断，而不是延长时间，以免无谓消耗时间。下一次更新会加上该判断。
感谢你的建议

**Comment by Kin-L** [comment]
已修
